// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useAuth from "@/app/lib/useAuth"; // Import the custom hook

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat Bot Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useAuth(); // Apply the authentication check here

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
