// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import AuthLayout from "@/app/components/AuthLayout";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ 
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "600", "700"]
});

export const metadata: Metadata = {
  title: "Chat Bot Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.variable}`}>
        <AuthLayout>{children}</AuthLayout> {/* Wrap in AuthLayout */}
      </body>
    </html>
  );
}
